apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ngrinder.agent.fullname" . }}
  labels:
    {{- include "ngrinder.agent.labels" . | nindent 4 }}
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "ngrinder.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ngrinder.agent.selectorLabels" . | nindent 8 }}
      {{- with .Values.agent.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with .Values.agent.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.agent.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ngrinder.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      {{- with .Values.agent.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args:
            - "{{ include "ngrinder.controller.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.controller.service.port }}"
          resources:
            {{- .Values.agent.resources | toYaml | trim | nindent 12 }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}