kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-workflow
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: development
roleRef:
  kind: ClusterRole
  name: argo-workflow
  apiGroup: rbac.authorization.k8s.io