apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
data:
  config: |
    [profile example-dev]
    role_arn = arn:aws:iam::...
    credential_source = Ec2InstanceMetadata
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-config
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: ...
        server: https://....ap-northeast-2.eks.amazonaws.com
      name: arn:aws:eks:ap-northeast-2:...
    contexts:
    - context:
        cluster: arn:aws:eks:ap-northeast-2:...
        user: arn:aws:eks:ap-northeast-2:...
      name: arn:aws:eks:ap-northeast-2:...
    current-context: arn:aws:eks:ap-northeast-2:...
    kind: Config
    preferences: {}
    users:
    - name: arn:aws:eks:ap-northeast-2:...
      user:
        exec:
          apiVersion: client.authentication.k8s.io/v1beta1
          args:
          - token
          - -i
          - example-dev
          - -r
          - arn:aws:iam::...
          command: aws-iam-authenticator