apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: development
stringData:
  username: kwangil77
  password: <path:kv/data/development/github#password>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config
stringData:
  config.json: |
    {
        "auths": {
            "ghcr.io": {
                "auth": "<path:kv/data/development/github#auth>"
            }
        }
    }
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
stringData:
  username: admin
  password: <path:kv/data/development/github#password>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
stringData:
  host.url: https://sonarqube.example.io
  token: <path:kv/data/development/sonarqube#token>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: dependency-track-secret
stringData:
  url: https://dependency-track.example.io
  api.key: <path:kv/data/development/dependency-track#api-key>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
stringData:
  username: deploy
  password: <path:kv/data/development/nexus#password>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
stringData:
  SLACK_WEBHOOK_URL: <path:kv/data/development/slack#api-url>
  SLACK_TOKEN: <path:kv/data/development/slack#token>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-secret
stringData:
  VAULT_ADDR: http://vault.provisioning:8200
  AVP_TYPE: vault
  AVP_AUTH_TYPE: k8s
  AVP_K8S_ROLE: argo-workflow
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: terraform-config
stringData:
  config.pg.tfbackend: |
    schema_name = "public"
    conn_str = "postgres://terraform:<path:kv/data/terraform/postgresql#password>@....ap-northeast-2.rds.amazonaws.com/terraform"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-batch
  labels:
    app: simple-batch
type: Opaque
stringData:
  SIMPLE_DATASOURCE_MASTER_PASSWORD: <path:kv/data/simple/simple/ds#password>
  SIMPLE_DATASOURCE_SLAVE_PASSWORD: <path:kv/data/simple/simple/ds#password>
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: developer-portal-batch
#   labels:
#     app: developer-portal-batch
# type: Opaque
# stringData:
#   DEVELOPERPORTAL_DATASOURCE_MASTER_PASSWORD: <path:kv/data/developer-portal/developer-portal/ds#password>
#   DEVELOPERPORTAL_DATASOURCE_SLAVE_PASSWORD: <path:kv/data/developer-portal/developer-portal/ds#password>
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  accessKey: <path:kv/data/minio/secret#access-key>
  secretKey: <path:kv/data/minio/secret#secret-key>
