apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: amazon-mq-create
spec:
  entrypoint: create
  podGC:
    strategy: OnPodCompletion
  arguments:
    parameters:
    - name: repo
      value: https://github.com/kwangil77/deployment.git
    - name: revision
      value: main
    - name: aws-profile
      value: example-dev
    - name: broker-name
      value: mq-dev
    - name: engine-type
      default: RabbitMQ
      enum:
      - RabbitMQ
    - name: engine-version
      value: 3.10.20
    - name: instance-type
      value: mq.t3.micro
    - name: deployment-mode
      default: SINGLE_INSTANCE
      enum:
      - SINGLE_INSTANCE
      - ACTIVE_STANDBY_MULTI_AZ
      - CLUSTER_MULTI_AZ
    - name: username
      value: admin
    - name: password
      value: admin1234567
    - name: tag-environment
      default: dev
      enum:
      - dev
      - qa
      - stage
      - prod
    - name: tag-server
      value: was
    - name: tag-service
      value: rabbitmq
    - name: tag-security-level
      default: moderate
      enum:
      - high
      - moderate
      - low
    - name: tag-team
      value: devops
    - name: tag-part
      value: devops
  templates:
  - name: create
    steps:
    - - name: create-broker
        template: create-broker
  - name: create-broker
    inputs:
      artifacts:
      - name: source
        path: /src
        git:
          repo: "{{ workflow.parameters.repo }}"
          revision: "{{ workflow.parameters.revision }}"
          usernameSecret:
            name: github-secret
            key: username
          passwordSecret:
            name: github-secret
            key: password
    volumes:
    - name: aws-config
      configMap:
        name: aws-config
        items:
        - key: config
          path: config
    - name: terraform-config
      secret:
        secretName: terraform-config
        items:
        - key: config.pg.tfbackend
          path: config.pg.tfbackend
    serviceAccountName: argo-workflow
    container:
      image: docker.io/hashicorp/terraform
      env:
      - name: AWS_PROFILE
        value: "{{ workflow.parameters.aws-profile }}"
      - name: AWS_DEFAULT_REGION
        value: ap-northeast-2
      command:
      - "/bin/sh"
      - "-c"
      args:
      - "
        cd /src/terraform/modules/mq
        && terraform init -backend-config=/root/.terraform/config.pg.tfbackend
        && terraform workspace new '{{ workflow.parameters.aws-profile }}:{{ workflow.parameters.broker-name }}' || terraform workspace select '{{ workflow.parameters.aws-profile }}:{{ workflow.parameters.broker-name }}'
        && terraform apply -auto-approve
          -var \"profile=${AWS_PROFILE}\"
          -var 'broker_name={{ workflow.parameters.broker-name }}'
          -var 'engine_type={{ workflow.parameters.engine-type }}'
          -var 'engine_version={{ workflow.parameters.engine-version }}'
          -var 'host_instance_type={{ workflow.parameters.instance-type }}'
          -var 'deployment_mode={{ workflow.parameters.deployment-mode }}'
          -var 'username={{ workflow.parameters.username }}'
          -var 'password={{ workflow.parameters.password }}'
          -var 'team={{ workflow.parameters.tag-team }}'
          -var 'server={{ workflow.parameters.tag-server }}'
          -var 'service={{ workflow.parameters.tag-service }}'
          -var 'security_level={{ workflow.parameters.tag-security-level }}'
          -var 'environment={{ workflow.parameters.tag-environment }}'
          -var 'part={{ workflow.parameters.tag-part }}'
        "
      workingDir: /src
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
      volumeMounts:
      - name: aws-config
        mountPath: /root/.aws/config
        subPath: config
      - name: terraform-config
        mountPath: /root/.terraform/config.pg.tfbackend
        subPath: config.pg.tfbackend
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: standard
