apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ec2-instance-create
spec:
  entrypoint: create
  podGC:
    strategy: OnPodCompletion
  arguments:
    parameters:
    - name: repo
      value: https://github.com/kwangil77/deployment.git
    - name: revision
      value: main
    - name: aws-profile
      value: example-dev
    - name: instance-name
      value: test-dev-grey
    - name: processor
      default: x86_64
      enum:
      - x86_64
      - arm64
    - name: instance-type
      value: t3.small
    - name: instance-count
      value: 1
    - name: tag-environment
      default: dev
      enum:
      - dev
      - qa
      - stage
      - prod
    - name: tag-server
      value: was
    - name: tag-service
      value: test
    - name: tag-security-level
      default: moderate
      enum:
      - high
      - moderate
      - low
    - name: tag-team
      value: devops
    - name: tag-part
      value: devops
  templates:
  - name: create
    steps:
    - - name: prepare-instance
        template: prepare-instance
    - - name: create-instance
        template: create-instance
        arguments:
          parameters:
          - name: role-arn
            value: "{{ steps.prepare-instance.outputs.parameters.role-arn }}"
  - name: prepare-instance
    outputs:
      parameters:
      - name: role-arn
        valueFrom:
          path: /tmp/role_arn
    volumes:
    - name: aws-config
      configMap:
        name: aws-config
        items:
        - key: config
          path: config
    serviceAccountName: argo-workflow
    container:
      image: ghcr.io/kwangil77/aws-handler
      env:
      - name: AWS_PROFILE
        value: "{{ workflow.parameters.aws-profile }}"
      - name: AWS_DEFAULT_REGION
        value: ap-northeast-2
      - name: CMDB_API_URL
        value: https://cmdb-api.example.io
      command:
      - "/bin/sh"
      - "-c"
      args:
      - "
        python3 -u /get_role_arn.py
          --tag-part {{ workflow.parameters.tag-part }}
        "
      workingDir: /
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
      volumeMounts:
      - name: aws-config
        mountPath: /root/.aws/config
        subPath: config
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: standard
  - name: create-instance
    inputs:
      artifacts:
      - name: source
        path: /src
        git:
          repo: "{{ workflow.parameters.repo }}"
          revision: "{{ workflow.parameters.revision }}"
          usernameSecret:
            name: github-secret
            key: username
          passwordSecret:
            name: github-secret
            key: password
      parameters:
      - name: role-arn
    volumes:
    - name: aws-config
      configMap:
        name: aws-config
        items:
        - key: config
          path: config
    - name: terraform-config
      secret:
        secretName: terraform-config
        items:
        - key: config.pg.tfbackend
          path: config.pg.tfbackend
    serviceAccountName: argo-workflow
    container:
      image: docker.io/hashicorp/terraform
      env:
      - name: AWS_PROFILE
        value: "{{ workflow.parameters.aws-profile }}"
      - name: AWS_DEFAULT_REGION
        value: ap-northeast-2
      command:
      - "/bin/sh"
      - "-c"
      args:
      - "
        cd /src/terraform/modules/ec2-instance
        && terraform init -backend-config=/root/.terraform/config.pg.tfbackend
        && terraform workspace new '{{ workflow.parameters.aws-profile }}:{{ workflow.parameters.instance-name }}' || terraform workspace select '{{ workflow.parameters.aws-profile }}:{{ workflow.parameters.instance-name }}'
        && terraform apply -auto-approve
          -var \"profile=${AWS_PROFILE}\"
          -var 'name={{ workflow.parameters.instance-name }}'
          -var 'processor={{ workflow.parameters.processor }}'
          -var 'instance_type={{ workflow.parameters.instance-type }}'
          -var 'instance_count={{ workflow.parameters.instance-count }}'
          -var 'team={{ workflow.parameters.tag-team }}'
          -var 'server={{ workflow.parameters.tag-server }}'
          -var 'service={{ workflow.parameters.tag-service }}'
          -var 'security_level={{ workflow.parameters.tag-security-level }}'
          -var 'environment={{ workflow.parameters.tag-environment }}'
          -var 'part={{ workflow.parameters.tag-part }}'
          -var 'role_arn={{ inputs.parameters.role-arn }}'
        "
      workingDir: /src
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
      volumeMounts:
      - name: aws-config
        mountPath: /root/.aws/config
        subPath: config
      - name: terraform-config
        mountPath: /root/.terraform/config.pg.tfbackend
        subPath: config.pg.tfbackend
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: standard
