apiVersion: v1
kind: Secret
metadata:
  name: terraform-config
stringData:
  config.pg.tfbackend: |
    schema_name = "public"
    conn_str = "postgres://terraform:<path:kv/data/terraform/postgresql#password>@....ap-northeast-2.rds.amazonaws.com/terraform"
type: Opaque