apiVersion: v1
kind: Service
metadata:
  name: simple-api-grpc
  annotations:
    konghq.com/protocol: grpc
spec:
  ports:
  - port: 9090
    protocol: TCP
  type: ExternalName
  externalName: simple-api-grpc.simple.svc.cluster.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-api-grpc
  annotations:
    konghq.com/protocols: grpc
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /main.User
        pathType: Prefix
        backend:
          service:
            name: simple-api-grpc
            port:
              number: 9090