apiVersion: v1
kind: Service
metadata:
  name: simple-api-rest
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: ExternalName
  externalName: simple-api.simple.svc.cluster.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-api-rest
  annotations:
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /simple-api/
        pathType: Prefix
        backend:
          service:
            name: simple-api-rest
            port:
              number: 8080