apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-ecr-proxy.fullname" . }}
  labels:
    {{- include "aws-ecr-proxy.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.config }}
  {{ $key }}: |-
{{ tpl $val $| indent 4 }}
{{- end }}