apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-ecr-proxy.fullname" . }}
  labels:
    {{- include "aws-ecr-proxy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ . | toYaml | trim | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aws-ecr-proxy.selectorLabels" . | nindent 4 }}