apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: backstage-techdocs-publish
spec:
  entrypoint: publish
  podGC:
    strategy: OnPodCompletion
  arguments:
    parameters:
    - name: repo
      value: https://github.com/kwangil77/backstage.git
    - name: revision
      value: main
  templates:
  - name: publish
    steps:
    - - name: execute
        template: execute
  - name: execute
    inputs:
      artifacts:
      - name: source
        path: /src
        git:
          repo: "{{ workflow.parameters.repo }}"
          revision: "{{ workflow.parameters.revision }}"
          usernameSecret:
            name: bitbucket-secret
            key: username
          passwordSecret:
            name: bitbucket-secret
            key: password
    serviceAccountName: argo-workflow
    container:
      image: harbor.example.io/devops/techdocs
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: accessKey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: secretKey
      - name: AWS_REGION
        value: ap-northeast-2
      command:
      - "/bin/sh"
      - "-c"
      args:
      - "
        techdocs-cli generate --no-docker --verbose
        && techdocs-cli publish --publisher-type awsS3 --awsEndpoint http://minio-hl.management:9000 --awsS3ForcePathStyle --storage-name example-dev-backstage-bucket --entity default/component/backstage
        "
      workingDir: /src
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: standard
