apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: simple-web
spec:
  template:
    serviceAccountName: argo-workflow
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: standard
  dependencies:
  - name: simple-web
    eventSourceName: argo-events
    eventName: bitbucket-server
    filters:
      dataLogicalOperator: and
      data:
      - path: body.repository.links.clone.#(name=="http").href
        type: string
        value:
        - https://github.com/kwangil77/simple-web.git
      - path: body.changes.0.ref.displayId
        type: string
        value:
        - main
  triggers:
  - template:
      name: simple-web-publish
      argoWorkflow:
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: simple-web-publish-
              namespace: development
              labels:
                workflows.argoproj.io/workflow-template: simple-web-publish
                submit-from-ui: 'true'
            spec:
              arguments:
                parameters:
                - name: repo
                  value: https://github.com/kwangil77/simple-web.git
                - name: revision
                  value: main
              workflowTemplateRef:
                name: simple-web-publish
        parameters:
        - src:
            dependencyName: simple-web
            dataKey: body.changes.0.ref.displayId
          dest: spec.arguments.parameters.1.value
  - template:
      name: simple-web-code-analysis
      argoWorkflow:
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: simple-web-code-analysis-
              namespace: development
              labels:
                workflows.argoproj.io/workflow-template: simple-web-code-analysis
                submit-from-ui: 'true'
            spec:
              arguments:
                parameters:
                - name: repo
                  value: https://github.com/kwangil77/simple-web.git
                - name: revision
                  value: main
              workflowTemplateRef:
                name: simple-web-code-analysis
        parameters:
        - src:
            dependencyName: simple-web
            dataKey: body.changes.0.ref.displayId
          dest: spec.arguments.parameters.1.value
  - template:
      name: simple-web-deps-analysis
      argoWorkflow:
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: simple-web-deps-analysis-
              namespace: development
              labels:
                workflows.argoproj.io/workflow-template: simple-web-deps-analysis
                submit-from-ui: 'true'
            spec:
              arguments:
                parameters:
                - name: repo
                  value: https://github.com/kwangil77/simple-web.git
                - name: revision
                  value: main
              workflowTemplateRef:
                name: simple-web-deps-analysis
        parameters:
        - src:
            dependencyName: simple-web
            dataKey: body.changes.0.ref.displayId
          dest: spec.arguments.parameters.1.value
  - template:
      name: simple-web-techdocs-publish
      argoWorkflow:
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: simple-web-techdocs-publish-
              namespace: development
              labels:
                workflows.argoproj.io/workflow-template: simple-web-techdocs-publish
                submit-from-ui: 'true'
            spec:
              arguments:
                parameters:
                - name: repo
                  value: https://github.com/kwangil77/simple-web.git
                - name: revision
                  value: main
              workflowTemplateRef:
                name: simple-web-techdocs-publish
        parameters:
        - src:
            dependencyName: simple-web
            dataKey: body.changes.0.ref.displayId
          dest: spec.arguments.parameters.1.value